const animeData={
 'one-piece':{title:'One Piece',desc:'Follow Monkey D. Luffy and the Straw Hat Pirates as they search for the legendary One Piece and the title of Pirate King.',rating:'8.7/10',year:'1999',status:'Ongoing',episodes:1120,genres:['Action','Adventure','Comedy','Fantasy'],languages:['Hindi Dub','English Dub','Original Audio','Fan Dub'],cls:'one'},
 'jujutsu-kaisen':{title:'Jujutsu Kaisen',desc:'A dark supernatural adventure filled with cursed energy, powerful sorcerers and unforgettable battles.',rating:'8.5/10',year:'2020',status:'Ongoing',episodes:47,genres:['Action','Drama','Fantasy'],languages:['Hindi Dub','English Dub','Original Audio'],cls:'jjk'},
 'demon-slayer':{title:'Demon Slayer',desc:'Tanjiro joins the Demon Slayer Corps after tragedy changes his family forever.',rating:'8.3/10',year:'2019',status:'Completed',episodes:63,genres:['Action','Adventure','Fantasy'],languages:['Hindi Dub','English Dub','Original Audio'],cls:'demon'},
 'attack-on-titan':{title:'Attack on Titan',desc:'Humanity fights for survival against terrifying Titans beyond the walls.',rating:'8.9/10',year:'2013',status:'Completed',episodes:89,genres:['Action','Drama','Fantasy'],languages:['Hindi Dub','English Dub','Original Audio'],cls:'aot'},
 'solo-leveling':{title:'Solo Leveling',desc:'A weak hunter gains a mysterious system that lets him level up beyond every limit.',rating:'8.4/10',year:'2024',status:'Ongoing',episodes:24,genres:['Action','Fantasy','Adventure'],languages:['Hindi Dub','English Dub','Original Audio'],cls:'solo'},
 'black-clover':{title:'Black Clover',desc:'Asta dreams of becoming the Wizard King despite being born without magic.',rating:'8.2/10',year:'2017',status:'Ongoing',episodes:170,genres:['Action','Adventure','Fantasy'],languages:['Hindi Dub','English Dub'],cls:'black'}
};
const genres=['Action','Adventure','Comedy','Drama','Fantasy','Horror','Mystery','Romance','Sci-Fi','Sports'];
const genreIcons=['✊','◉','●','◆','♞','☠','⌕','♥','◌','⚽'];
function card(id){const a=animeData[id];return `<article class="card"><a href="anime.html?anime=${id}"><div class="poster ${a.cls}"><span class="badge">HD</span><b>${a.title}</b></div><h3>${a.title}</h3><small>TV • ${a.episodes}+ Episodes</small></a></article>`}
function renderHome(){if(!document.getElementById('trendingCards'))return;const ids=Object.keys(animeData);document.getElementById('trendingCards').innerHTML=ids.map(card).join('');document.getElementById('recentCards').innerHTML=ids.slice(1,5).map(card).join('');document.getElementById('movieCards').innerHTML=ids.slice(2,5).map(card).join('');document.getElementById('genreGrid').innerHTML=genres.map((g,i)=>`<a class="genre" href="#anime"><span class="ico">${genreIcons[i]}</span><small>${g}</small></a>`).join('');document.getElementById('hindiList').innerHTML=ids.slice(0,5).map(id=>`<a class="list-item" href="anime.html?anime=${id}"><div class="thumb ${animeData[id].cls}"></div><div><strong>${animeData[id].title}</strong><small>Hindi Dub • Available</small></div></a>`).join('');renderContinue();renderMyList();}
function renderContinue(){const box=document.getElementById('continueBox');if(!box)return;const p=JSON.parse(localStorage.getItem('animeFanProgress')||'null');if(!p){box.innerHTML='<div class="muted">No saved progress yet. Start an episode and your browser will remember your position.</div>';return}const a=animeData[p.anime]||animeData['one-piece'];const mins=Math.floor(p.time/60),secs=String(Math.floor(p.time%60)).padStart(2,'0');box.innerHTML=`<a class="continue-item" href="watch.html?anime=${p.anime}&episode=${p.episode}"><div class="mini-poster ${a.cls}">▶</div><div style="flex:1"><strong>${a.title} — Episode ${p.episode}</strong><small class="muted">Resume at ${mins}:${secs}</small><div class="progress"><span style="width:${Math.min(100,(p.time/(p.duration||1))*100)}%"></span></div></div><span class="btn primary">Resume</span></a>`}
function renderMyList(){const box=document.getElementById('myListBox');if(!box)return;const ids=JSON.parse(localStorage.getItem('animeFanList')||'[]');box.innerHTML=ids.length?ids.map(id=>`<a class="list-item" href="anime.html?anime=${id}"><div class="thumb ${animeData[id]?.cls||''}"></div><div><strong>${animeData[id]?.title||id}</strong><small>Saved on this browser</small></div></a>`).join(''):'<div class="muted">Your My List is empty. Add anime from a details page.</div>'}
function renderDetail(){const root=document.getElementById('detailApp');if(!root)return;const id=new URLSearchParams(location.search).get('anime')||'one-piece',a=animeData[id]||animeData['one-piece'];root.innerHTML=`<section class="container detail-hero"><div class="detail-inner"><div class="detail-poster ${a.cls}">✦</div><div class="detail-copy"><span class="eyebrow">${a.status.toUpperCase()}</span><h1>${a.title}</h1><p class="muted">${a.desc}</p><div class="chips">${a.genres.map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="detail-info"><div class="info"><small>Rating</small>⭐ ${a.rating}</div><div class="info"><small>Year</small>${a.year}</div><div class="info"><small>Episodes</small>${a.episodes}</div><div class="info"><small>Languages</small>${a.languages.length}</div></div><div class="selects" style="margin-top:18px"><select id="detailLang">${a.languages.map(x=>`<option>${x}</option>`).join('')}</select><select><option>Season 01</option><option>Season 02</option></select></div><div class="hero-actions"><a class="btn primary" href="watch.html?anime=${id}&episode=1">▶ Watch Now</a><button class="btn ghost" onclick="toggleList('${id}')">＋ Add to My List</button></div></div></div></section><section class="container section"><div class="section-head"><h2>Episodes</h2><span class="muted">${a.episodes} episodes</span></div><div class="cards compact">${[1,2,3,4].map(n=>`<a class="card" href="watch.html?anime=${id}&episode=${n}"><div class="poster ${a.cls}"><span class="badge">${n}</span><b>Episode ${String(n).padStart(2,'0')}</b></div><h3>${a.title}</h3><small>23:40 • ${a.languages[0]}</small></a>`).join('')}</div></section>`}
function toggleList(id){let l=JSON.parse(localStorage.getItem('animeFanList')||'[]');l=l.includes(id)?l.filter(x=>x!==id):[...l,id];localStorage.setItem('animeFanList',JSON.stringify(l));alert(l.includes(id)?'Added to My List':'Removed from My List');}
function renderWatch(){const root=document.getElementById('watchApp');if(!root)return;const q=new URLSearchParams(location.search),id=q.get('anime')||'one-piece',ep=Number(q.get('episode')||1),a=animeData[id]||animeData['one-piece'];root.innerHTML=`<main class="container watch-main"><div class="watch-layout"><div><div class="player-wrap"><div class="player"><div class="player-placeholder">▶<b>${a.title} — Episode ${String(ep).padStart(2,'0')}</b><span>Connect an authorized video URL in the backend/API.</span></div></div><div class="watch-bar"><div class="selects"><select id="watchLang">${a.languages.map(x=>`<option>${x}</option>`).join('')}</select><select><option>Season 01</option><option>Season 02</option></select></div><div class="watch-actions"><button class="btn ghost" onclick="likeVideo()">❤️ Like</button><button class="btn ghost" onclick="shareVideo()">🔗 Share</button><button class="btn ghost" onclick="reportVideo()">⚠ Report</button><button class="btn primary" onclick="downloadGate('episode')">⬇ Download</button></div></div></div><div class="watch-title"><h1>${a.title} — Episode ${String(ep).padStart(2,'0')}</h1><p class="muted">${a.desc}</p><div class="hero-actions"><a class="btn ghost" href="watch.html?anime=${id}&episode=${Math.max(1,ep-1)}">◀ Previous</a><a class="btn primary" href="watch.html?anime=${id}&episode=${Math.min(a.episodes,ep+1)}">Next Episode ▶</a></div></div><div class="comment-box"><h2>💬 Comments</h2><form id="commentForm" class="form"><textarea id="commentText" required placeholder="Write a comment..."></textarea><button class="btn primary">Post Comment</button></form><div id="comments"></div></div></div><aside class="episodes"><div class="section-head"><h2>Episodes</h2><span class="muted">1–20</span></div>${Array.from({length:20},(_,i)=>i+1).map(n=>`<a class="episode ${n===ep?'active':''}" href="watch.html?anime=${id}&episode=${n}"><span class="episode-num">${n}</span><span style="flex:1">Episode ${String(n).padStart(2,'0')}<small class="muted">23:40 • ${a.languages[0]}</small></span><span>›</span></a>`).join('')}</aside></div></main>`;document.getElementById('commentForm').addEventListener('submit',e=>{e.preventDefault();const text=document.getElementById('commentText').value.trim();if(!text)return;const key='animeFanComments';const c=JSON.parse(localStorage.getItem(key)||'[]');c.unshift({text,time:new Date().toLocaleString()});localStorage.setItem(key,JSON.stringify(c));document.getElementById('commentText').value='';renderComments()});renderComments();localStorage.setItem('animeFanProgress',JSON.stringify({anime:id,episode:ep,time:923,duration:1420}));}
function renderComments(){const box=document.getElementById('comments');if(!box)return;const c=JSON.parse(localStorage.getItem('animeFanComments')||'[]');box.innerHTML=c.map(x=>`<div class="comment"><b>Guest Fan</b><p>${escapeHtml(x.text)}</p><small class="muted">❤️ 0 • ↩ Reply • ${x.time}</small></div>`).join('')||'<p class="muted">Be the first to comment.</p>'}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function likeVideo(){alert('Like saved locally in this browser (demo).')}function shareVideo(){navigator.clipboard?.writeText(location.href).then(()=>alert('Watch link copied.')).catch(()=>alert(location.href))}function reportVideo(){const r=prompt('Report reason: video not working / wrong episode / wrong audio / subtitle / other');if(r)localStorage.setItem('lastReport',r)}function downloadGate(type){const count=type==='movie'?3:2;alert(`${count} ad(s) are configured before download in this demo. Connect your authorized ad provider and download URL in the backend.`)}
function setupHome(){renderHome();const s=document.getElementById('search');if(s)s.addEventListener('input',()=>{const q=s.value.toLowerCase();document.querySelectorAll('#trendingCards .card').forEach(c=>c.style.display=c.innerText.toLowerCase().includes(q)?'':'none')});const f=document.getElementById('requestForm');if(f)f.addEventListener('submit',e=>{e.preventDefault();const r=JSON.parse(localStorage.getItem('animeFanRequests')||'[]');r.push({name:reqName.value,season:reqSeason.value,audio:reqAudio.value,message:reqMessage.value,status:'Pending'});localStorage.setItem('animeFanRequests',JSON.stringify(r));requestStatus.textContent='Request submitted • Status: Pending';f.reset()});document.getElementById('themeBtn')?.addEventListener('click',()=>document.body.classList.toggle('light'))}
function setupAdmin(){const login=document.getElementById('adminLogin');if(!login)return;const show=()=>{document.getElementById('loginPanel').classList.add('hidden');document.getElementById('dashboard').classList.remove('hidden');renderAdmin()};if(sessionStorage.getItem('animeFanAdmin')==='1')show();login.addEventListener('submit',e=>{e.preventDefault();if(adminUser.value==='admin'&&adminPass.value==='admin123'){sessionStorage.setItem('animeFanAdmin','1');show()}else loginMsg.textContent='Demo login: admin / admin123'});document.getElementById('logout')?.addEventListener('click',()=>{sessionStorage.removeItem('animeFanAdmin');location.reload()})}
function renderAdmin(){const list=document.getElementById('adList');if(!list)return;let ads=JSON.parse(localStorage.getItem('animeFanAds')||'["05:00","18:00","30:00","50:00","70:00","90:00","110:00","130:00","150:00"]');const draw=()=>list.innerHTML=ads.map((x,i)=>`<input data-i="${i}" value="${x}">`).join('');draw();document.getElementById('addAd').onclick=()=>{ads.push('00:00');draw()};document.getElementById('saveAds').onclick=()=>{ads=[...list.querySelectorAll('input')].map(x=>x.value);localStorage.setItem('animeFanAds',JSON.stringify(ads));alert('Ad schedule saved locally.');};document.getElementById('requestCount').textContent=JSON.parse(localStorage.getItem('animeFanRequests')||'[]').length}
setupHome();renderDetail();renderWatch();setupAdmin();
